owner: pritesh-1904
repo: moto-monitor-upptime
sites:
  - name: MotoShare India
    url: https://motoshare.in
    ssl: true
  - name: MotoShare Colombia
    url: https://motoshare.co
    ssl: true
  - name: MotoShare Indonesia
    url: https://motoshare.id
    ssl: true
  - name: MotoShare China (.com.cn)
    url: https://motoshare.com.cn
    ssl: true
  - name: MotoShare Mexico
    url: https://motoshare.mx
    ssl: true
  - name: MotoShare USA
    url: https://motoshare.us
    ssl: true
  - name: MotoShare Japan
    url: https://motoshare.jp
    ssl: true
  - name: MotoShare Gulf
    url: https://motosharegulf.com
    ssl: true
  - name: MotoShare Asia
    url: https://motoshare.asia
    ssl: true
  - name: MotoShare Africa
    url: https://motoshareafrica.com
    ssl: true
assignees:
  - pritesh-1904
status-website:
  cname: 
  baseUrl: /moto-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MotoShare Uptime Monitor
  introTitle: "MotoShare Websites Uptime and SSL Status"
  introMessage: This is a status page monitoring the uptime and SSL certificates of MotoShare websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/pritesh-1904/moto-monitor-upptime
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
committer:
  email: pritesh.cotocus@gmail.com
  name: Pritesh

